--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements

--insert into Member (id, name,  email, phone_number) values (0, 'John', 'john.smith@mailinator.com', '2125551212') 
--insert into Member (id, firstname, lastname, email, phone_number) values (1, 'Andrew', 'Smith', 'andrew.smith@mailinator.com', '2125559999')
--insert into Member (id, firstname, lastname, email, phone_number) values (2, 'Johan' , 'Pettersson', 'johan.pettersson@mailinator.com', '2125551212') 


insert into Member (id, firstname, lastname,  email, phone_number, address) values (0, 'John', 'Smith', 'john.smith@mailinator.com', '2125551212',  ' ');
insert into Member (id, firstname, lastname, email, phone_number,  address) values (1, 'Andrew', 'Smith', 'andrew.smith@mailinator.com', '2125559999',  ' ');
insert into Member (id, firstname, lastname, email, phone_number,  address) values (2, 'Johan' , 'Pettersson', 'johan.pettersson@mailinator.com', '2125551212',  ' ') ;
insert into Member (id, firstname, lastname, email, phone_number,  address) values (3, 'Olle' , 'Smith', 'olle.smith@mailinator.com', '2125559999', ' ');

INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (11, 'Jeffrey Archer', 'Modern Times', '1-86092-049-7', 399, 'Available','The Grass is Always Greener', 'This ingenious tale examines the ambitions and petty jealousies of the staff at Critchley´s Bank. From the doorman to the personnel manager, to Sir William, the bank´s sorrowful chairman. Archer knits a panoply of characters with deft narrative skill in a story which is as revealing as it is observant. Taken from his anthology To Cut a Long Story Short, his other short story anthologies include A Quiver Full of Arrows, Twelve Red Herrings and A Twist in the Tale.','<img src="http://covers.openlibrary.org/b/isbn/1860920497-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (12, 'Arnold Bennett (1867-1931)', 'Crime', '1-86092-012-8', 399, 'Available','Murder!', 'Two men meet in a seaside resort. What follows is murder. What´s discovered isn´t all it seems to be... Arnold Bennett was born in 1867. He wrote an influential book column for the Evening Standard from 1926 until his death in London in 1931. He was a great admirer of the French realists and his most successful novels, Clayhanger, Hilda Lessways, and These Twain, set in his native Staffordshire, show the literary influence of Flaubert and Balzac on his work. He also wrote plays and essays, as well as many short stories.','<img src="http://covers.openlibrary.org/b/isbn/1860920128-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (13, 'Ambrose Bierce (1842-1914)', 'Adventure', '1-86092-006-3', 399, 'Available','An Occurrence at Owl Creek Bridge One of the Missing', 'Ambrose Bierce was an American journalist, newspaper editor, misanthrope, writer and wit. His two short story masterpieces, An Occurrence at Owl Creek Bridge and One of the Missing, are both brilliant examples of American short fiction at its sharpest. Each is a gripping action tale set in the American Civil War during which Bierce himself saw action at Shiloh and Chickamauga. He was seriously wounded on Kenesaw Mountain in 1864 and promoted to Major in 1867. His death remains an unsolved mystery, - the most likely theory is that he was a fatality of the siege at Ojinaga during the Mexican revolution of 1914.','<img src="http://covers.openlibrary.org/b/isbn/1860920063-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (14, 'John Bidwell', 'First Edition', '1-86092-022-5', 399, 'Available','Fear and Loathing in Aspen', 'John Bidwell´s two satirical short story journals are loosely based on real incidents in the author´s life. A Boy at Seven is set in a Jesuit boarding school in the early 1960s where some of the boys, fed up with their hateful and sadistic Prefect of Discipline, Father John Kilbracken, hatch a plan to humiliate him in front of all. In Fear and Loathing in Aspen, the author observes the strange behaviour of Americans at the famous Colorado skiing resort of Aspen and follows one of them, a hairy billionaire called Abe Fineblown, on a gung-ho shooting mission to Kenya.','<img src="http://covers.openlibrary.org/b/isbn/1860920225-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (15, 'A. E. Coppard (1878-1957)', 'Romance', '1-86092-010-1', 399, 'Available','The Higgler', 'Alfred Edgar Coppard, the son of a Kentish journeyman tailor and a hosteler´s daughter, wrote his first short story at the age of 43 and achieved fame in his lifetime, for his vivid depictions of the English countryside and its rural characters. The Higgler, which first appeared in his anthology Fishmonger´s Fiddle in 1925, is one of his finest works; a strangely unpredictable tale of an itinerant dealer in poultry and eggs whose emotional involvement with the mother and daughter of an isolated farmhouse on the moors threatens to become an obsession.','<img src="http://covers.openlibrary.org/b/isbn/1860920101-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (16, 'Stephen Crane (1871-1900)', 'Classic', '1-86092-025-x', 399, 'Available','The Open Boat', 'The Open Boat is a captivating short story based on a real-life event. On January 1st 1897, the great American writer, Stephen Crane, was sailing in the steamer, Commadore, which was running arms from Florida to rebels resisting Spanish domination in Cuba. Crane was a war correspondent at the time. The Commodore sank and Crane was cast adrift in an open boat with three or four crew members, including the captain, Edward Murphy. This the dramatic story of what happened next.','<img src="http://covers.openlibrary.org/b/isbn/186092025x-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (17, 'Roald Dahl (1916-1990)', 'N/A', '1-86092-034-9', 399, 'Available','The Great Switcheroo', 'Roald Dahl was a master story teller who during his lifetime achieved phenomenal success with tales both for children and adults. The Great Switcheroo, which first appeared in Dahl´s diminutive collection, Switch Bitch, is a decidedly adult fable. Vic Hammond is "churning with lust" for his neighbour, Samantha Rainbow. But Vic is married, and so is Samantha (to Vic´s best friend, Jerry). Undeterred the lecherous Mr Hammond devises a very strange scheme.','<img src="http://covers.openlibrary.org/b/isbn/1860920349-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (18, 'Sir Arthur Conan Doyle (1859-1930)', 'Crime', '1-86092-003-9', 399, 'Available','The Speckled Band', 'In one of the most thrilling and inventive of all Sherlock Holmes stories, the Baker Street detective and his trusted friend, Dr. Watson, are called to the aid of a mysterious lady who is convinced that her life is in danger. Sir Arthur Conan Doyle creates an inimitable atmosphere of intrigue and suspense leading to an investigation at Stoke Moran, the creepy Surrey mansion of a certain Dr Grimesby Roylott.','<img src="http://covers.openlibrary.org/b/isbn/1860920039-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (19, 'Charles Dickens (1812-1870)', 'Suspense', '1-86092-038-1', 399, 'Available','The Signalman', '´The slow touch of a frozen finger´ will trace your spine as the tale of a spectre warning a signalman of impending disaster unfolds. It was first published in the Christmas 1866 edition of All The Year Round - a journal edited by Charles Dickens himself. The timing is significant, as Dickens had been involved in a serious train crash at Staplehurst in the summer of 1865, in which several people died. Obviously deeply affected by the tragedy, he went on to write this classic ghost story.','<img src="http://covers.openlibrary.org/b/isbn/1860920381-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (20, 'Arthur Conan Doyle', 'Crime', '1-86092-031-4', 399, 'Available','The Five Orange Pips', 'In this classic Sherlock Holmes mystery the famous Baker Street detective is confronted with one of the most baffling cases of his entire career. Members of the Openshaw family are one-by-one being murdered. Holmes must find a pattern and a motive to these crimes before another member of the family is killed....but there are very few clues. Will the great man fathom the meaning of the five orange pips in time?','<img src="http://covers.openlibrary.org/b/isbn/1860920314-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (21, 'Daniel Etessami', 'First Edition', '1-86092-039-X', 399, 'Available','Cormack´s Black Monday/Gerald´s Day Off/Fat Boy Billy Rules the Middle Lane', 'Born in Tehran in 1972, the brilliant young writer Daniel Etessami was brought up in Germany before moving to London. The three extraordinary stories published here share a common theme – obsessiveness. In the first, Cormack aspires to become an international business tycoon; in the second, Gerald strives to come to terms with his addiction to timetables; while, in the final story, Fat Boy Billy risks life and limb to maintain control at his local swimming pool.','<img src="http://covers.openlibrary.org/b/isbn/186092039X-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (22, 'F. Scott Fitzgerald (1896-1940)', 'Science Fiction', '1-86092-033-0', 399, 'Available','The Diamond as Big as the Ritz', 'Scott Fitzgerald´s extraordinary fantasy was written in the winter of 1921-1922. John T. Unger, a middle class American boy from a small town on the Mississippi River goes, for his summer holiday, to stay for the first time with an enigmatic school friend, Percy Washington. On the journey out Percy confides with an abrupt remark: "My father is by far the richest man in the world." "The Schnlitzer Murphys had diamonds as big as walnuts - " "That´s nothing," Percy had leaned forward and dropped his voice to a low whisper. "That´s nothing at all. My father has a diamond bigger than the Ritz-Carlton Hotel."','<img src="http://covers.openlibrary.org/b/isbn/1860920330-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (23, 'Ian Fleming (1908-1964)', 'Adventure', '1-86092-055-1', 399, 'Available','From a View to a Kill', 'James Bond is on a mission in France. Ian Fleming, his creator, was a senior naval intelligence officer during World War II, and drew from personal experience in writing his 12 novels and seven short stories featuring the fictional British Secret Service agent, James Bond, 007. Our image of James Bond has been usurped by the world-famous series of films featuring, among others Sean Connery, Roger Moore and Timothy Dalton as Bond. But the real Bond is a far more intriguing character than the films lead us to believe. The spy-thriller, From a View to a Kill, first appeared in Ian Fleming´s short story collection For your Eyes Only in 1962.','<img src="http://covers.openlibrary.org/b/isbn/1860920551-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (24, 'C. S. Forester (1899-1966)', 'Adventure', '1-86092-014-4', 399, 'Available','The Hostage', 'Cecil Scott Forester is best known for his historical novels, particularly those about the British naval officer, Horatio Hornblower. The Hostage is a Second World War story taken from the point of view of a German General, Friederich von Dexter, who receives hysterical orders from the Fuehrer, Adolf Hitler, in the dying days of the War. He must obey his orders or face the fatal Nazi punishments for military disobedience, but can he also save the lives of the ten thousand ordinary German soldiers under his command?','<img src="http://covers.openlibrary.org/b/isbn/1860920144-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (25, 'Graham Greene (1904-1991)', 'Classic', '1-86092-021-7', 399, 'Available','A Chance for Mr Lever', 'A Chance for Mr Lever A Chance for Mr Lever is one of Graham Greene´s most memorable short story masterpieces. "I believe I have never written anything better," he wrote in 1975. At a very low ebb Mr Lever, a retired machinery salesman who has lost his money in the depression, rashly accepts a commission-only job which sends him out on a gamble to Africa. He must find a man called Davidson and secure his signature to a contract. Everything depends on finding Davidson. Mr Lever´s once cosy life is now hanging in the balance far, far away in the sweat of a remote African jungle.','<img src="http://covers.openlibrary.org/b/isbn/1860920217-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (26, 'Thomas Hardy (1840-1928)', 'Romance', '1-86092-045-4', 399, 'Available','A Mere Interlude', 'Thomas Hardy is best remembered for his passionate poems and the series of Wessex novels which included Jude the Obscure, Far from the Madding Crowd and Tess of the Durbevilles. The short story, A Mere Interlude, is an absorbing masterpiece with as many twists and turns as any plot in Hardy. A school teacher from the mainland returns to the island home of her childhood to be married to a man who is not altogether to her liking. But she meets another on her way and, in a moment of wildness, all her plans go seriously awry. This is a story of passion and cover-up; a tale of love, destiny and heroism in the best tradition of Thomas Hardy.','<img src="http://covers.openlibrary.org/b/isbn/1860920454-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (27, 'Jerome K. Jerome (1859-1927)', 'Comedy', '1-86092-050-0', 399, 'Available','The Dancing Partner: Clocks', 'Most famous for his classic, comic novel Three Men in a Boat (1889), which describes a rowing holiday on the Thames enjoyed by three men and their dog, Jerome K. Jerome first published The Dancing Partner three years later in Novel Notes. It is about as black as humour can get. An inventor creates a machine that can dance with all the girls at new society balls, but the results are far from satisfactory. Still in mechanical vain, this edition includes Jerome´s little-known short, comic essay, Clocks.','<img src="http://covers.openlibrary.org/b/isbn/1860920500-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (28, 'D. H. Lawrence (1885-1930)', 'Classic', '1-86092-007-1', 399, 'Available','The Rocking-Horse Winner', 'A Fragment of Stained Glass The Rocking-Horse Winner, which first appeared in Cynthia Asquith´s Ghost Book of 1926, is one of D. H Lawrence´s best known stories; an eerily supernatural tale about a small boy who is determined to reverse his family´s continuiing ill-fortune by winning huge amounts of money at the races. In A Fragment of Stained Glass monks at an old abbey believe they have seen the Devil trying to break in through a stained glass window. But what was really happening? Many years later a local parish priest thinks he has the answer.','<img src="http://covers.openlibrary.org/b/isbn/1860920071-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (29, 'Katherine Mansfield (1888-1923)', 'Romance', '1-86092-005-5', 399, 'Available','Bliss Feuille d´Album', 'In Bliss (1920) Bertha Young, a happily married mother, gives a small dinner-party for a theatre director and his wife, a whey-faced poet and a new friend for whom she feels a strange burning affinity. "What can you do if you are thirty and, turning the corner of your own street, you are overcome, suddenly by a feeling of bliss - absolute bliss?". Feuille D´Album is an equally strange and compelling story about a handsome young artist working in Paris. "How could one resist him?" But it does not take people long to notice that the fascinating Mr French is not all that he seems to be.','<img src="http://covers.openlibrary.org/b/isbn/1860920055-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (30, 'Ngaio Marsh (1899-1982)', 'Crime', '1-86092-020-9', 399, 'Available','Death on the Air', 'Featuring the famous detective, Roderick Alleyn, Death on the Air is a classic murder-mystery Who-Dunnit? Septimus Tonks is found dead beside his wireless set. "His hands, the fingers curiously bunched, were on the ledge of the cabinet under the tuning and volume knobs. His chest rested against the shelf below and his head leaned on the front panel." Was it a heart attack? Suspicious Detective Alleyn is searching for a weapon and a motive, he needs to interview everyone in the house - someone must be hiding the truth.','<img src="http://covers.openlibrary.org/b/isbn/1860920209-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (31, 'Guy de Maupassant (1850-1893)', 'Classic', '1-86092-009-8', 399, 'Available','Mademoiselle Fifi', 'Guy de Maupassant´s sharpness, brilliance and wit made him the most popular short story writer of his day. In Mademoiselle Fifi, set during the Franco-Prussian war of 1870-1871, a loutish and destructive band of Prussian officers has taken over a beautiful French Ch‰teau. They call in some prostitutes to eleviate their boredom but the evening goes badly wrong. In The Devil a young peasant farmer, fretting over the expense of his elderly mother´s imminent death, strikes a deal with an odious old ironing woman.','<img src="http://covers.openlibrary.org/b/isbn/1860920098-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (32, 'Ivo Mosley', 'Sex', '1-86092-018-7', 399, 'Available','Christmas in Africa', 'Doctor Dennet stared at the enormous set of equipment in front of her. Even without being erect, it was quite obviously of exceptional size. The thought of it erect quite boggled her mind. So begins the strange tale of Frank who sets out on a fantastic trip to the heart of tribal Africa in search of the sexual satisfaction which has so far eluded him in England. Christmas in Africa, a comedy, a love story, an erotic fable and a thrilling adventure, is published here for the very first time.','<img src="http://covers.openlibrary.org/b/isbn/1860920187-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (33, 'edited and introduced by Ivo Mosley', 'Poetry', '1-86092-026-8', 399, 'Available','Love Poems from the Green Book of Poetry', 'Drawn from Ivo Mosley´s hugely successful Green Book of Poetry, Poems of Love are picked from a rich treasury of world verse which includes such wide ranging poets as Shakespeare, Matthew Arnold and Li Po, each extolling the virtues of love in unique and various ways - from the pornographic desires of Robert Burns to the subtle longings of the Japanese poet Hitomaro, this is an absorbing collection. Ivo Mosley is Poetry Editor of The Journal of Consciousness Studies and wrote the best-selling erotic story, Christmas in Africa, for the Travelman Sex series in 1998.','<img src="http://covers.openlibrary.org/b/isbn/1860920268-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (34, 'O Henry (1862-1910)', 'Crime', '1-86092-011-x', 399, 'Available','The Ransom of Red Chief; Gift of the Magi', 'O Henry, whose real name was William Sydney Porter, was born in South Carolina, USA. He was convicted on a charge of embezzlement in 1896 and wrote his first short stories from prison. O Henry´s humorous and ingenius plots soon earned him a reputation as one of the most popular short story writers of his day. In The Ransom of Red Chief two outlaws kidnap an unruly child and soon come to regret it. The Gift of Magi is one of O Henry´s most celebrated stories.','<img src="http://covers.openlibrary.org/b/isbn/186092011x-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (35, 'Dorothy Parker (1893-1967)', 'Comedy', '1-86092-017-9', 399, 'Available','A Telephone Call', 'Dorothy Parker is remembered as much today for her sparkling short stories as for her poems and her witty remarks. In Here We Are a newly wedded couple prepares for the first evening of a honeymoon in New York. Both he and she face the stark possibility that marriage may not be quite as jolly as they had each anticipated. In A Telephone Call Parker´s satiric wit is focussed on a hapless and frantic girl as she waits impatiently by the telephone praying that her lover will ring.','<img src="http://covers.openlibrary.org/b/isbn/1860920179-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (36, 'Edgar Allan Poe (1809-1849)', 'Suspense', '1-86092-019-5', 399, 'Available','The Pit and the Pendulum', 'Edgar Allan Poe was born in Boston, his parents were itinerent actors. At the age of two he was taken into care by a wealthy tobacco exporter, John Allan, from whom the author took his middle name. His first collection of stories, Tales of the Grotesque and Arabesque was published in 1840 and contains some of his most famous works. In his classic suspense story, The Pit and the Pendulum, which first appeared in1842, a man awakes from an unconscious state to find himself lying on his back in pitch darkness. He has no idea how he got there; his nightmare begins.','<img src="http://covers.openlibrary.org/b/isbn/1860920195-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (37, 'John Polidori (1795-1821)', 'Suspense', '1-86092-035-7', 399, 'Available','The Vampyre', 'This fascinating Gothic horror story introduces us to Lord Ruvthen, the father of all vampires, and the future inspiration for Count Dracula and the whole genre of blood sucking thrillers which are still popular today. Polidori was a doctor, of Italian parentage, from Edinburgh. He travelled to Geneva with Lord Byron, but they quarrelled. Returning home, Polidori published The Vampyre in the 1819 issue of the New Monthly Magazine, pretending it was by Byron. The poet refuted it, admitting only that he had been working on a story of the same title. However Polidori´s The Vampyre soon became the talk of Europe and was turned into an opera by the German composer, Heinrich Marschner.','<img src="http://covers.openlibrary.org/b/isbn/1860920357-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (38, 'Edna O´Brien', 'Romance', '1-86092-036-5', 399, 'Available','Irish Revel', 'In Irish Revel Edna O´Brien explores the naive world of a young Irish girl, Mary, who is brought up in an isolated farmhouse and invited, aged seventeen, to a party for the first time in her life. Dressed in her mother´s finest lace, she rides her bicycle to the Commercial Hotel in a state of high anticipation, but the party is not all that she expected it to be. Irish Revel first appeared in the short story collection The Love Object in 1968 and is one of Edna O´Brien´s most moving works.','<img src="http://covers.openlibrary.org/b/isbn/1860920365-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (39, 'Ruth Rendell', 'Crime', '1-86092-032-2', 399, 'Available','Thornapple', 'Ruth Rendell´s mysteries have become famous throughout the world. In Thornapple James Fyfield, a young boy with an enquiring, scientific mind, takes up a very unusual hobby - making deadly poisons in his mother´s kitchen when she is out. Soon he has a large collection of jars tucked away on a the top shelf in his bedroom - hemlock, henblane and deadly nightshade. But the one of which he is proudest by far is a murky brown concoction, painstakingly prepared from the spiky fruit of the thornapple.','<img src="http://covers.openlibrary.org/b/isbn/1860920322-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (40, 'Saki (1870-1916)', 'Comedy', '1-86092-013-6', 399, 'Available','Sredni Vashtar, The Secret Sin Septimus Brope,The Lumber Room', 'Hector Hugh Monro (alias Saki) was one the most accomplished short story writers of the English language, and the three stories printed here are brilliant examples of his wit and ingenuity in this form. The Secret Sin of Septimus Brope, and Sredni Vashtar both first appeared in the short story collection, The Chronicles of Clovis (1912). The Lumber-Room, an account of a young boy´s escape from the domineering authority of his bossy aunts, was published two years later in Saki´s popular collection entitled Beasts and Super-Beasts.','<img src="http://covers.openlibrary.org/b/isbn/1860920136-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (41, 'Muriel Spark', 'First Edition', '1-86092-015-2', 399, 'Available','The Young Man who Discovered the Secret of Life', 'The Snobs The Pearly Shadow A relationship between a young man and the ghost that haunts his bedroom forms the basis of this brilliant, symbolic little story by Muriel Spark. It is published here, for the first time, in the Travelman First Edition Series. The Snobs is likewise a satire with a twist; set in a French ch‰teau owned by a modest couple under threat of invasion from a pair of castle-crawling snobs. The Pearly Shadow deftly resumes the spirit theme of the first story. Dame Muriel is an honoured member of the Travelman Short Stories Editorial Board.','<img src="http://covers.openlibrary.org/b/isbn/1860920152-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (42, 'Robert Louis Stevenson (1850-1894)', 'Suspense', '1-86092-001-2', 399, 'Available','The Body Snatcher', 'This gruesome story was first published in the Christmas issue of the Pall Mall Magazine for 1884 and, although it had been written some time earlier, Stevenson initially laid it aside "in justifiable disgust, the tale being horrid." One night Fettes, an old Scotsman at the George Inn, is shocked out of his drunkenness by the sudden appearance of a shady figure from his past, Dr Wolfe Macfarlane. The sight of Macfarlane brings back terrible memories for Fettes, in particular, the nightmarish events of that stormy night in a rustic graveyard at Glencorse.','<img src="http://covers.openlibrary.org/b/isbn/1860920012-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (43, 'Bram Stoker (1847-1912)', 'Suspense', '1-86092-008-x', 399, 'Available','The Judge´s House', 'Famous as the author of Dracula, Bram Stoker, the master of terror, was born in Dublin. He could neither stand nor walk until the age of seven but later overcame his physical weaknesses as an outstanding athlete. He worked as a civil servant in Dublin and afterwards as a personal assistant to the celebrated actor, Sir Henry Irving. In The Judge´s House a scholar seeking solitide finds himself in the rustic village of Benchurch. Ignoring the warnings of terrified locals he wilfully takes up residence in a sinister house, once the property of an infamous and evil judge.','<img src="http://covers.openlibrary.org/b/isbn/186092008x-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (44, 'William Trevor', 'First Edition', '1-86092-041-1', 399, 'Available','The Summer Visitor', 'Every September for thirteen years Guy has taken Monsieur and Madame Buissonnet out to dinner at M. Perdreau´s delicious hotel-restaurant; but this occasion is different from all the others. Guy will never be able to forget what happened on this particular night and (maybe), if he is lucky, Monsieur and Madame Buissonnet will never know. William Trevor, one of the most distinguished short story writers of our modern age has written this remarkable and moving tale for Travelman Short Story Editions. He is an honoured member of the Travelman Editorial Board.','<img src="http://covers.openlibrary.org/b/isbn/1860920411-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (45, 'Evelyn Waugh (1903-1966)', 'Comedy', '1-86092-000-4', 399, 'Available','On Guard, Bella Fleace Gave a Party', 'In each of these early short stories, Evelyn Waugh´s black humour and satiric skill are both at their sharpest. The poodle, Hector, takes a central role in On Guard (1932), fiercely defending his putty-nosed mistress, Millicent Blade, from the advances of unwanted suitors. In Bella Fleace Gave a Party (1934), an octogenarian Irish aristocrat prepares her crumbling mansion for a great evening of festivities, but things don´t necessarily all go to plan.','<img src="http://covers.openlibrary.org/b/isbn/1860920004-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (46, 'Teresa Waugh', 'First Edition', '1-86092-030-6', 399, 'Available','A Perfect Day', 'Teresa Waugh, the celebrated novelist, has written many beautifully crafted short-stories. In this, A Perfect Day, written especially for the Travelman First Edition series, Ellis, a seemingly ordinary man, is killed in a car crash. Celia, his twin sister, comes to the funeral and is visited by a flood of haunting memories which reveal the extraordinarily breathless tale of her brother´s life and the effect that he, and his wicked ways, had on her own peculiar past. Teresa Waugh´s latest novel A Friend Like Harvey is published by Gollancz in June 1999.','<img src="http://covers.openlibrary.org/b/isbn/1860920306-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (47, 'H.G. Wells (1866-1946)', 'Science Fiction', '1-86092-002-0', 399, 'Available','Country of the Blind', 'In one of H. G. Wells´s most brilliant and haunting stories, Nunez, a hapless mountaineer falls several thousand feet down the side of an Andean mountain to find himself in the Country of the Blind, a sealed-off valley, where, for fifteen generations, a strange community of congenitally blind human beings has been thriving in complete ignorance of the outside world. Nunez gleefully reminds himself of an old proverb: "In the Country of the Blind, the One-Eyed Man is King," but, to his dismay, things do not happen quite as he had hoped. The Country of the Blind was written in 1904 and first published, in book form, in 1911.','<img src="http://covers.openlibrary.org/b/isbn/1860920020-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (48, 'Oscar Wilde (1854-1900)', 'Classic', '1-86092-016-0', 399, 'Available','Lord Savile´s Crime', 'Lord Arthur Savile´s Crime, first published in 1887, opens at Lady Windermere´s society soirŽe in London. A chiromantist, Mr Septimus Podgers, has been brought to the party to entertain the assembled guests. All goes well until he examines Lord Arthur Savile´s hand: "Podgers grew curiously pale, and said nothing. A shudder seemed to pass through him. Then some huge beads of perspiration broke out on his yellow forehead, like a poisonous dew, and his fat fingers grew cold and clammy...."','<img src="http://covers.openlibrary.org/b/isbn/1860920160-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (49, 'Wilkie Collins (1824-1889)', 'Suspense', '1-86092-042-X', 399, 'Available','The Traveller´s Story of a Terribly Strange Bed', 'A close friend of Charles Dickens, Wilkie Collins became a popular and highly successful writer of Victorian mysteries; his most famous novels being The Woman in White and The Moonstone. In The Traveller´s Story of a Terribly Strange Bed (1852) a young Englishman expresses his desire to experience ´a little genuine, blackguard, poverty-stricken gaming´ during a sojourn in Paris, little realising that his success at the gaming table would lead him into mortal danger.','<img src="http://covers.openlibrary.org/b/isbn/186092042X-M.jpg" />');
INSERT INTO BOOK (ID, AUTHOR, GENRE, ISBN, PAGES, STATUS, TITLE, INFO, IMAGE) VALUES (50, 'P. G. Wodehouse (1881-1975)', 'Comedy', '1-86092-004-7', 399, 'Available','Goodbye to all Cats', 'Freddie Widgeon, anxious to make a good impression, visits Matcham Scratchings, the home of his beloved, Dahlia Prenderby. But its animal occupants soon turn his stay into a disastrous and hilarious farce... P. G. Wodehouse is the most popular of all quintessentially English humorists. He wrote over 120 volumes, creating such famous figures as Bertie Wooster and his butler, Jeeves, Lord Emsworth and his famous sow, the Empress of Blandings, Psmith, Mulliner and a host of other memorably comic characters. After a scandal during the Second World War, he moved permanently to America, becoming a US citizen in 1955.','<img src="http://covers.openlibrary.org/b/isbn/1860920047-M.jpg" />');


insert into Book (id, author, createdyear , genre , isbn, pages, position, title, status) values ('1','Leif GW Persson', '2018', 'Thriller', '978-91-642-2082-0', 399, 'F4', 'Grisfesten','Available')
insert into Book (id, author, createdyear , genre , isbn, pages, position, title, status) values ('2','Leif GW Svensson', '1988', 'Thriller', '978-91-642-2082-1', 399, 'F4', 'Grispesten','Available')
insert into Book (id, author, createdyear , genre , isbn, pages, position, title, status) values ('3','Leif GW Olsson', '1946', 'Thriller', '978-91-642-2082-2', 399, 'F4', 'Grisfoten','Available')
insert into Book (id, author, createdyear , genre , isbn, pages, position, title, status) values ('4','Leif GW Vang', '2014', 'Thriller', '978-91-642-2082-3', 399, 'F4', 'Grisörat','Available')
insert into Book (id, author, createdyear , genre , isbn, pages, position, title, status) values ('5','Leif GW Doyle', '2010', 'Thriller', '978-91-642-2082-4', 399, 'F4', 'Griskasslern','Available')

 

